# Generated by Django 4.1.3 on 2022-12-03 12:21

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='photo',
            field=models.ImageField(null=True, upload_to=api.models.upload_category_to),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='category',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
