# Generated by Django 4.1.3 on 2022-12-03 18:29

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categorymodel_photo_alter_categorymodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='photo',
            field=models.ImageField(null=True, upload_to=api.models.upload_category_to, verbose_name='image_url'),
        ),
    ]
