# Generated by Django 4.1.3 on 2022-12-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_categorymodel_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='photo',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='categorymodel',
            old_name='category',
            new_name='name',
        ),
    ]
