# Generated by Django 4.1.3 on 2022-12-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_photo_categorymodel_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='image_url',
            new_name='imageUrl',
        ),
    ]
