# Generated by Django 4.1.3 on 2022-12-03 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_image_url_categorymodel_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='imageUrl',
            new_name='image_url',
        ),
    ]
