# Generated by Django 4.1.3 on 2022-12-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_photo_photomodel_imageurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomodel',
            name='imageUrl',
            field=models.CharField(max_length=200),
        ),
    ]
